CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Itens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(150) NOT NULL,
    "Preco" numeric NOT NULL,
    "Ativo" boolean NOT NULL,
    CONSTRAINT "PK_Itens" PRIMARY KEY ("Id")
);

CREATE TABLE "Pedidos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(20) NOT NULL,
    "Cliente" text NULL,
    "TipoPedido" character varying(20) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Observacao" text NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "DataConclusao" timestamp with time zone NULL,
    "ValorTotal" numeric NOT NULL,
    CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id")
);

CREATE TABLE "ItensPedidos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PedidoId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "PrecoUnitario" numeric NOT NULL,
    "TotalItem" numeric NOT NULL,
    CONSTRAINT "PK_ItensPedidos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ItensPedidos_Itens_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Itens" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ItensPedidos_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ItensPedidos_ItemId" ON "ItensPedidos" ("ItemId");

CREATE INDEX "IX_ItensPedidos_PedidoId" ON "ItensPedidos" ("PedidoId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251128152246_InitialPostgres', '6.0.32');

COMMIT;

