CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Empresas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cnpj" character varying(18) NOT NULL,
    "Nome" character varying(200) NOT NULL,
    "RazaoSocial" character varying(200) NOT NULL,
    "Seguimento" character varying(100) NOT NULL,
    CONSTRAINT "PK_Empresas" PRIMARY KEY ("Id")
);

CREATE TABLE "Perfis" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    CONSTRAINT "PK_Perfis" PRIMARY KEY ("Id")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(200) NOT NULL,
    "Nome" character varying(150) NOT NULL,
    "Senha" character varying(200) NOT NULL,
    "EmpresaId" integer NOT NULL,
    "PerfilId" integer NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Usuarios_Empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES "Empresas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Usuarios_Perfis_PerfilId" FOREIGN KEY ("PerfilId") REFERENCES "Perfis" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Itens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(150) NOT NULL,
    "Preco" numeric NOT NULL,
    "Ativo" boolean NOT NULL,
    "EmpresaId" integer NOT NULL,
    CONSTRAINT "PK_Itens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Itens_Empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES "Empresas" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Pedidos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(20) NOT NULL,
    "Cliente" text NULL,
    "TipoPedido" character varying(20) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Observacao" text NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    "DataConclusao" timestamp with time zone NULL,
    "ValorTotal" numeric NOT NULL,
    "EmpresaId" integer NOT NULL,
    CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pedidos_Empresas_EmpresaId" FOREIGN KEY ("EmpresaId") REFERENCES "Empresas" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ItensPedidos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PedidoId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "PrecoUnitario" numeric NOT NULL,
    "TotalItem" numeric NOT NULL,
    CONSTRAINT "PK_ItensPedidos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ItensPedidos_Itens_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Itens" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ItensPedidos_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Usuarios_EmpresaId" ON "Usuarios" ("EmpresaId");
CREATE INDEX "IX_Usuarios_PerfilId" ON "Usuarios" ("PerfilId");
CREATE INDEX "IX_Itens_EmpresaId" ON "Itens" ("EmpresaId");
CREATE INDEX "IX_Pedidos_EmpresaId" ON "Pedidos" ("EmpresaId");
CREATE INDEX "IX_ItensPedidos_ItemId" ON "ItensPedidos" ("ItemId");
CREATE INDEX "IX_ItensPedidos_PedidoId" ON "ItensPedidos" ("PedidoId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251128152246_InitialPostgres', '6.0.32');

COMMIT;

-- Admin helper functions
CREATE OR REPLACE FUNCTION "sp_Admin_Usuarios_ListarPorEmpresa"(empresa_id INT)
RETURNS TABLE(
    "Id" INT,
    "Email" TEXT,
    "Nome" TEXT,
    "PerfilId" INT,
    "PerfilNome" TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        u."Id",
        u."Email",
        u."Nome",
        u."PerfilId",
        COALESCE(p."Nome", '') AS "PerfilNome"
    FROM "Usuarios" u
    LEFT JOIN "Perfis" p ON p."Id" = u."PerfilId"
    WHERE u."EmpresaId" = empresa_id;
END;
$$;

CREATE OR REPLACE FUNCTION "sp_Admin_Empresa_Obter"(empresa_id INT)
RETURNS TABLE(
    "Id" INT,
    "Cnpj" TEXT,
    "Nome" TEXT,
    "RazaoSocial" TEXT,
    "Seguimento" TEXT
)
LANGUAGE sql
AS $$
    SELECT "Id", "Cnpj", "Nome", "RazaoSocial", "Seguimento"
    FROM "Empresas"
    WHERE "Id" = empresa_id;
$$;

-- Dashboard stored functions (PostgreSQL)
-- Atualizam as consultas usadas pelos endpoints de dashboard.

CREATE OR REPLACE FUNCTION "sp_Dashboard_HorariosPico_DiaSemanaDistribuicao"("DataInicio" DATE, "DataFim" DATE, "EmpresaId" INT)
RETURNS TABLE(
    "DiaSemana" SMALLINT,
    "NomeDia" TEXT,
    "Hora" INT,
    "QuantidadePedidos" BIGINT,
    "Faturamento" NUMERIC(18,2)
)
LANGUAGE plpgsql
AS $$
DECLARE
    inicio DATE := "DataInicio";
    fim    DATE := "DataFim";
    empresa INT := "EmpresaId";
BEGIN
    -- Usa o primeiro e o ultimo pedido finalizado da empresa caso nao receba datas
    IF inicio IS NULL OR fim IS NULL THEN
        SELECT
            COALESCE(inicio, MIN("DataCriacao"::DATE)),
            COALESCE(fim,    MAX("DataCriacao"::DATE))
        INTO inicio, fim
        FROM "Pedidos"
        WHERE "Status" = 'Finalizado'
          AND "EmpresaId" = empresa;
    END IF;

    IF inicio IS NULL OR fim IS NULL OR empresa IS NULL THEN
        RETURN;
    END IF;

    RETURN QUERY
    WITH dias_semana AS (
        SELECT *
        FROM (
            VALUES
                (1::SMALLINT, 'Segunda'::TEXT),
                (2::SMALLINT, 'Terca'::TEXT),
                (3::SMALLINT, 'Quarta'::TEXT),
                (4::SMALLINT, 'Quinta'::TEXT),
                (5::SMALLINT, 'Sexta'::TEXT),
                (6::SMALLINT, 'Sabado'::TEXT),
                (7::SMALLINT, 'Domingo'::TEXT)
        ) AS x("DiaSemana", "NomeDia")
    ),
    base AS (
        SELECT
            (CASE
                WHEN EXTRACT(DOW FROM p."DataCriacao")::INT = 0 THEN 7
                ELSE EXTRACT(DOW FROM p."DataCriacao")::INT
             END)::SMALLINT                       AS "DiaSemana",
            EXTRACT(HOUR FROM p."DataCriacao")::INT AS "Hora",
            COUNT(*)::BIGINT                      AS "QuantidadePedidos",
            SUM(p."ValorTotal")::NUMERIC(18,2)    AS "Faturamento"
        FROM "Pedidos" p
        WHERE p."Status" = 'Finalizado'
          AND p."EmpresaId" = empresa
          AND p."DataCriacao"::DATE BETWEEN inicio AND fim
        GROUP BY
            (CASE
                WHEN EXTRACT(DOW FROM p."DataCriacao")::INT = 0 THEN 7
                ELSE EXTRACT(DOW FROM p."DataCriacao")::INT
             END),
            EXTRACT(HOUR FROM p."DataCriacao")
    )
    SELECT
        b."DiaSemana",
        d."NomeDia",
        b."Hora",
        b."QuantidadePedidos",
        b."Faturamento"
    FROM base b
    INNER JOIN dias_semana d ON d."DiaSemana" = b."DiaSemana"
    ORDER BY b."DiaSemana", b."Hora";
END;
$$;

CREATE OR REPLACE FUNCTION "sp_Dashboard_HorariosPico_DiaSemanaResumo"("DataInicio" DATE, "DataFim" DATE, "EmpresaId" INT)
RETURNS TABLE(
    "DiaSemana" SMALLINT,
    "NomeDia" TEXT,
    "Hora" INT,
    "QuantidadePedidos" BIGINT,
    "Faturamento" NUMERIC(18,2)
)
LANGUAGE plpgsql
AS $$
DECLARE
    inicio DATE := "DataInicio";
    fim    DATE := "DataFim";
    empresa INT := "EmpresaId";
BEGIN
    -- Usa o primeiro e o ultimo pedido finalizado da empresa caso nao receba datas
    IF inicio IS NULL OR fim IS NULL THEN
        SELECT
            COALESCE(inicio, MIN("DataCriacao"::DATE)),
            COALESCE(fim,    MAX("DataCriacao"::DATE))
        INTO inicio, fim
        FROM "Pedidos"
        WHERE "Status" = 'Finalizado'
          AND "EmpresaId" = empresa;
    END IF;

    -- Sem pedidos: devolve todos os dias com zero
    IF inicio IS NULL OR fim IS NULL OR empresa IS NULL THEN
        RETURN QUERY
        SELECT
            d."DiaSemana",
            d."NomeDia",
            0::INT           AS "Hora",
            0::BIGINT        AS "QuantidadePedidos",
            0::NUMERIC(18,2) AS "Faturamento"
        FROM (
            VALUES
                (1::SMALLINT, 'Segunda'::TEXT),
                (2::SMALLINT, 'Terca'::TEXT),
                (3::SMALLINT, 'Quarta'::TEXT),
                (4::SMALLINT, 'Quinta'::TEXT),
                (5::SMALLINT, 'Sexta'::TEXT),
                (6::SMALLINT, 'Sabado'::TEXT),
                (7::SMALLINT, 'Domingo'::TEXT)
        ) AS d("DiaSemana", "NomeDia")
        ORDER BY d."DiaSemana";
        RETURN;
    END IF;

    RETURN QUERY
    WITH dias_semana AS (
        SELECT *
        FROM (
            VALUES
                (1::SMALLINT, 'Segunda'::TEXT),
                (2::SMALLINT, 'Terca'::TEXT),
                (3::SMALLINT, 'Quarta'::TEXT),
                (4::SMALLINT, 'Quinta'::TEXT),
                (5::SMALLINT, 'Sexta'::TEXT),
                (6::SMALLINT, 'Sabado'::TEXT),
                (7::SMALLINT, 'Domingo'::TEXT)
        ) AS x("DiaSemana", "NomeDia")
    ),
    base AS (
        SELECT
            (CASE
                WHEN EXTRACT(DOW FROM p."DataCriacao")::INT = 0 THEN 7
                ELSE EXTRACT(DOW FROM p."DataCriacao")::INT
             END)::SMALLINT                       AS "DiaSemana",
            EXTRACT(HOUR FROM p."DataCriacao")::INT AS "Hora",
            COUNT(*)::BIGINT                      AS "QuantidadePedidos",
            SUM(p."ValorTotal")::NUMERIC(18,2)    AS "Faturamento"
        FROM "Pedidos" p
        WHERE p."Status" = 'Finalizado'
          AND p."EmpresaId" = empresa
          AND p."DataCriacao"::DATE BETWEEN inicio AND fim
        GROUP BY
            (CASE
                WHEN EXTRACT(DOW FROM p."DataCriacao")::INT = 0 THEN 7
                ELSE EXTRACT(DOW FROM p."DataCriacao")::INT
             END),
            EXTRACT(HOUR FROM p."DataCriacao")
    )
    SELECT
        d."DiaSemana",
        d."NomeDia",
        COALESCE(r."Hora", 0)                       AS "Hora",
        COALESCE(r."QuantidadePedidos", 0)          AS "QuantidadePedidos",
        COALESCE(r."Faturamento", 0::NUMERIC(18,2)) AS "Faturamento"
    FROM dias_semana d
    LEFT JOIN LATERAL (
        SELECT
            b."Hora",
            b."QuantidadePedidos",
            b."Faturamento"
        FROM base b
        WHERE b."DiaSemana" = d."DiaSemana"
        ORDER BY b."QuantidadePedidos" DESC,
                 b."Faturamento"       DESC,
                 b."Hora"
        LIMIT 1
    ) r ON TRUE
    ORDER BY d."DiaSemana";
END;
$$;

CREATE OR REPLACE FUNCTION "sp_Dashboard_HorariosPico_Periodo"("DataInicio" DATE, "DataFim" DATE, "EmpresaId" INT)
RETURNS TABLE(
    "Hora" INT,
    "QuantidadePedidos" BIGINT,
    "Faturamento" NUMERIC(18,2)
)
LANGUAGE plpgsql
AS $$
DECLARE
    inicio DATE := "DataInicio";
    fim    DATE := "DataFim";
    empresa INT := "EmpresaId";
BEGIN
    -- Usa o primeiro e o ultimo pedido finalizado da empresa caso nao receba datas
    IF inicio IS NULL OR fim IS NULL THEN
        SELECT
            COALESCE(inicio, MIN("DataCriacao"::DATE)),
            COALESCE(fim,    MAX("DataCriacao"::DATE))
        INTO inicio, fim
        FROM "Pedidos"
        WHERE "Status" = 'Finalizado'
          AND "EmpresaId" = empresa;
    END IF;

    IF inicio IS NULL OR fim IS NULL OR empresa IS NULL THEN
        RETURN;
    END IF;

    RETURN QUERY
    SELECT
        EXTRACT(HOUR FROM p."DataCriacao")::INT AS "Hora",
        COUNT(*)::BIGINT                        AS "QuantidadePedidos",
        SUM(p."ValorTotal")::NUMERIC(18,2)      AS "Faturamento"
    FROM "Pedidos" p
    WHERE p."Status" = 'Finalizado'
      AND p."EmpresaId" = empresa
      AND p."DataCriacao"::DATE BETWEEN inicio AND fim
    GROUP BY EXTRACT(HOUR FROM p."DataCriacao")
    ORDER BY "Hora";
END;
$$;

CREATE OR REPLACE FUNCTION "sp_Dashboard_ItensRanking"("DataInicio" DATE, "DataFim" DATE, "EmpresaId" INT)
RETURNS TABLE(
    "ItemId" INT,
    "Nome" TEXT,
    "QuantidadeVendida" INT,
    "Faturamento" NUMERIC(18,2)
)
LANGUAGE plpgsql
AS $$
DECLARE
    inicio DATE := "DataInicio";
    fim    DATE := "DataFim";
    empresa INT := "EmpresaId";
BEGIN
    -- Usa o primeiro e o ultimo pedido finalizado da empresa caso nao receba datas
    IF inicio IS NULL OR fim IS NULL THEN
        SELECT
            COALESCE(inicio, MIN("DataCriacao"::DATE)),
            COALESCE(fim,    MAX("DataCriacao"::DATE))
        INTO inicio, fim
        FROM "Pedidos"
        WHERE "Status" = 'Finalizado'
          AND "EmpresaId" = empresa;
    END IF;

    IF inicio IS NULL OR fim IS NULL OR empresa IS NULL THEN
        RETURN;
    END IF;

    RETURN QUERY
    SELECT
        i."Id" AS "ItemId",
        i."Nome"::TEXT,
        SUM(ip."Quantidade")::INT          AS "QuantidadeVendida",
        SUM(ip."TotalItem")::NUMERIC(18,2) AS "Faturamento"
    FROM "ItensPedidos" ip
    INNER JOIN "Pedidos" p ON p."Id" = ip."PedidoId"
    INNER JOIN "Itens"   i ON i."Id" = ip."ItemId"
    WHERE p."Status" = 'Finalizado'
      AND p."EmpresaId" = empresa
      AND p."DataCriacao"::DATE BETWEEN inicio AND fim
    GROUP BY i."Id", i."Nome"
    ORDER BY "QuantidadeVendida" DESC, "Faturamento" DESC;
END;
$$;

CREATE OR REPLACE FUNCTION "sp_Dashboard_ResumoPeriodo"("DataInicio" DATE, "DataFim" DATE, "EmpresaId" INT)
RETURNS TABLE(
    "QtdePedidos" BIGINT,
    "FaturamentoTotal" NUMERIC(18,2),
    "TicketMedio" NUMERIC(18,2),
    "QtdeDiasPeriodo" INTEGER,
    "MediaClientesPorDia" NUMERIC(18,2)
)
LANGUAGE plpgsql
AS $$
DECLARE
    inicio      DATE := "DataInicio";
    fim         DATE := "DataFim";
    empresa     INT := "EmpresaId";
    diasPeriodo INTEGER;
BEGIN
    -- Usa o primeiro e o ultimo pedido finalizado da empresa caso nao receba datas
    IF inicio IS NULL OR fim IS NULL THEN
        SELECT
            COALESCE(inicio, MIN("DataCriacao"::DATE)),
            COALESCE(fim,    MAX("DataCriacao"::DATE))
        INTO inicio, fim
        FROM "Pedidos"
        WHERE "Status" = 'Finalizado'
          AND "EmpresaId" = empresa;
    END IF;

    IF inicio IS NULL OR fim IS NULL OR empresa IS NULL THEN
        RETURN QUERY
        SELECT
            0::BIGINT           AS "QtdePedidos",
            0::NUMERIC(18,2)    AS "FaturamentoTotal",
            0::NUMERIC(18,2)    AS "TicketMedio",
            0::INTEGER          AS "QtdeDiasPeriodo",
            0::NUMERIC(18,2)    AS "MediaClientesPorDia";
        RETURN;
    END IF;

    diasPeriodo := (fim - inicio) + 1;

    RETURN QUERY
    SELECT
        COUNT(*)::BIGINT                                      AS "QtdePedidos",
        COALESCE(SUM(p."ValorTotal"), 0)::NUMERIC(18,2)       AS "FaturamentoTotal",
        CASE
            WHEN COUNT(*) = 0 THEN 0::NUMERIC(18,2)
            ELSE (SUM(p."ValorTotal") / COUNT(*))::NUMERIC(18,2)
        END                                                   AS "TicketMedio",
        diasPeriodo                                           AS "QtdeDiasPeriodo",
        CASE
            WHEN diasPeriodo = 0 THEN 0::NUMERIC(18,2)
            ELSE (COUNT(*)::NUMERIC(18,2) / diasPeriodo)
        END                                                   AS "MediaClientesPorDia"
    FROM "Pedidos" p
    WHERE p."Status" = 'Finalizado'
      AND p."EmpresaId" = empresa
      AND p."DataCriacao"::DATE BETWEEN inicio AND fim;
END;
$$;

CREATE OR REPLACE FUNCTION "sp_Dashboard_TipoPedido"("DataInicio" DATE, "DataFim" DATE, "EmpresaId" INT)
RETURNS TABLE(
    "TipoPedido" TEXT,
    "QtdePedidos" BIGINT,
    "Faturamento" NUMERIC(18,2)
)
LANGUAGE plpgsql
AS $$
DECLARE
    inicio DATE := "DataInicio";
    fim    DATE := "DataFim";
    empresa INT := "EmpresaId";
BEGIN
    -- Usa o primeiro e o ultimo pedido finalizado da empresa caso nao receba datas
    IF inicio IS NULL OR fim IS NULL THEN
        SELECT
            COALESCE(inicio, MIN("DataCriacao"::DATE)),
            COALESCE(fim,    MAX("DataCriacao"::DATE))
        INTO inicio, fim
        FROM "Pedidos"
        WHERE "Status" = 'Finalizado'
          AND "EmpresaId" = empresa;
    END IF;

    IF inicio IS NULL OR fim IS NULL OR empresa IS NULL THEN
        RETURN;
    END IF;

    RETURN QUERY
    SELECT
        p."TipoPedido"::TEXT,
        COUNT(*)::BIGINT                   AS "QtdePedidos",
        SUM(p."ValorTotal")::NUMERIC(18,2) AS "Faturamento"
    FROM "Pedidos" p
    WHERE p."Status" = 'Finalizado'
      AND p."EmpresaId" = empresa
      AND p."DataCriacao"::DATE BETWEEN inicio AND fim
    GROUP BY p."TipoPedido";
END;
$$;
